package com.insightsystems.dal;

import java.util.HashMap;
import java.util.Map;

public class NeatConstants {
    protected static final String BASE_URI = "/api/v1";
    protected static final String LOGIN_URI = "admin_login";
    protected static final String STATUS_URI = "status";
    protected static final String AV_URI = "settings/audiovideo";
    protected static final String SYSTEM_URI = "settings/system";
    protected static final String UPDATES_URI = "settings/updates";
    protected static final String TIME_URI = "settings/time";
    protected static final String NTP_URI = "settings/time/ntp";
    protected static final String LANGUAGE_URI = "settings/language";
    protected static final String REBOOT_URI = "device/reboot";
    protected static final Map<String, String> PRODUCT_MAP = new HashMap<>() {{
        put("arran", "Neat Pad");
        put("barra", "Neat Bar");
        put("fettercairn","Neat Frame");
    }};
    protected static final Map<String, String> ANTIBANDING_MODES = new HashMap<>() {{
        put("Default","default");
        put("50 Hz","50");
        put("60 Hz","60");
    }};

    protected static final Map<String,String> UPDATE_CHANNEL_MAP = new HashMap<>(){{
       put("Stable","stable");
       put("Preview","beta");
    }};

    protected static final Map<Boolean, String> UPDATE_TYPE_MAP = new HashMap<>(){{
        put(true,"AUTOMATIC");
        put(false,"MANUAL");
    }};
    protected static final Map<String,String> TIMEZONE_MAP = new HashMap<>() {{
        put("Midway","Pacific/Midway");
        put("Honolulu","Pacific/Honolulu");
        put("Anchorage","America/Anchorage");
        put("Los Angeles","America/Los_Angeles");
        put("Tijuana","America/Tijuana");
        put("Phoenix","America/Phoenix");
        put("Chihuahua","America/Chihuahua");
        put("Denver","America/Denver");
        put("Costa Rica","America/Costa_Rica");
        put("Regina","America/Regina");
        put("Chicago","America/Chicago");
        put("Mexico City","America/Mexico_City");
        put("Bogota","America/Bogota");
        put("New York","America/New_York");
        put("Caracas","America/Caracas");
        put("Barbados","America/Barbados");
        put("Manaus","America/Manaus");
        put("Halifax","America/Halifax");
        put("Santiago","America/Santiago");
        put("Recife","America/Recife");
        put("Sao Paulo","America/Sao_Paulo");
        put("Buenos Aires","America/Argentina/Buenos_Aires");
        put("Montevideo","America/Montevideo");
        put("St. John’s","America/St_Johns");
        put("Nuuk","America/Godthab");
        put("South Georgia","Atlantic/South_Georgia");
        put("Cape Verde","Atlantic/Cape_Verde");
        put("Azores","Atlantic/Azores");
        put("GMT","GMT");
        put("Casablanca","Africa/Casablanca");
        put("London","Europe/London");
        put("Brazzaville","Africa/Brazzaville");
        put("Amsterdam","Europe/Amsterdam");
        put("Belgrade","Europe/Belgrade");
        put("Berlin","Europe/Berlin");
        put("Oslo","Europe/Oslo");
        put("Brussels","Europe/Brussels");
        put("Madrid","Europe/Madrid");
        put("Paris","Europe/Paris");
        put("Rome","Europe/Rome");
        put("Sarajevo","Europe/Sarajevo");
        put("Warsaw","Europe/Warsaw");
        put("Windhoek","Africa/Windhoek");
        put("Cairo","Africa/Cairo");
        put("Harare","Africa/Harare");
        put("Amman","Asia/Amman");
        put("Athens","Europe/Athens");
        put("Istanbul","Europe/Istanbul");
        put("Beirut","Asia/Beirut");
        put("Helsinki","Europe/Helsinki");
        put("Jerusalem","Asia/Jerusalem");
        put("Minsk","Europe/Minsk");
        put("Baghdad","Asia/Baghdad");
        put("Moscow","Europe/Moscow");
        put("Kuwait","Asia/Kuwait");
        put("Nairobi","Africa/Nairobi");
        put("Tehran","Asia/Tehran");
        put("Baku","Asia/Baku");
        put("Tbilisi","Asia/Tbilisi");
        put("Yerevan","Asia/Yerevan");
        put("Dubai","Asia/Dubai");
        put("Kabul","Asia/Kabul");
        put("Karachi","Asia/Karachi");
        put("Oral","Asia/Oral");
        put("Yekaterinburg","Asia/Yekaterinburg");
        put("Kolkata","Asia/Kolkata");
        put("Colombo","Asia/Colombo");
        put("Kathmandu","Asia/Kathmandu");
        put("Almaty","Asia/Almaty");
        put("Yangon","Asia/Yangon");
        put("Krasnoyarsk","Asia/Krasnoyarsk");
        put("Bangkok","Asia/Bangkok");
        put("Jakarta","Asia/Jakarta");
        put("Shanghai","Asia/Shanghai");
        put("Hong Kong","Asia/Hong_Kong");
        put("Irkutsk","Asia/Irkutsk");
        put("Kuala Lumpur", "Asia/Kuala_Lumpur");
        put("Perth","Australia/Perth");
        put("Taipei","Asia/Taipei");
        put("Seoul","Asia/Seoul");
        put("Tokyo","Asia/Tokyo");
        put("Yakutsk","Asia/Yakutsk");
        put("Darwin","Australia/Darwin");
        put("Brisbane","Australia/Brisbane");
        put("Vladivostok","Asia/Vladivostok");
        put("Guam","Pacific/Guam");
        put("Adelaide","Australia/Adelaide");
        put("Hobart","Australia/Hobart");
        put("Sydney","Australia/Sydney");
        put("Magadan","Asia/Magadan");
        put("Noumea","Pacific/Noumea");
        put("Majuro","Pacific/Majuro");
        put("Fiji","Pacific/Fiji");
        put("Auckland","Pacific/Auckland");
        put("Tongatapu","Pacific/Tongatapu");
    }};
    
    protected static Map<String,String> LANGUAGE_MAP = new HashMap<>(){{
        put("German","de");
        put("English","en-US");
        put("Spanish","es");
        put("French","fr");
        put("Italian","it");
        put("Japanese","ja-JP");
        put("Korean","ko");
        put("Norwegian Bokmål","nb");
        put("Polish","pl");
        put("Portuguese","pt");
        put("Russian","ru");
        put("Swedish","sv");
        put("Turkish","tr");
        put("Chinese (Simplified Han)","zh-Hans");;
        put("Chinese (Traditional Han)","zh-Hant");
    }};
}
